import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "./component/Navbar";
import "./globals.css";


const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
})

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased max-w-360 mx-auto`}
      >
        <div className="bg-white border-x border-gray-200 ">
          
        <Navbar />
        {children }
        </div>
      </body>
    </html>
  );
}
